
CREATE DATABASE FShark_V2;
go
USE FShark_V2;
go
CREATE TABLE TYPES (
    ID INT IDENTITY PRIMARY KEY,
    TYLE NVARCHAR(100)
);
go

GO
CREATE TABLE USERROLES (
    ID INT IDENTITY PRIMARY KEY,
    ROLE NVARCHAR(100)
);
GO
CREATE TABLE USERS (
    USERNAME VARCHAR(200) PRIMARY KEY,
    ROLES INT,
	PASSWORD VARCHAR(30),
    ACTIVE BIT,
    EMAIL VARCHAR(200),
    GENDER BIT,
    LASTNAME NVARCHAR(100),
    FIRSTNAME NVARCHAR(100),
    BIRTHDAY DATE,
    BIO  NVARCHAR(500),
    HOMETOWN NVARCHAR(200),
	CURRENCY NVARCHAR(100),
	FOREIGN KEY (ROLES) REFERENCES USERROLES(ID),
);
GO
CREATE TABLE POSTS (
    ID INT IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(200),
    CONTENT NVARCHAR(200),
    CREATEDATE DATETIME,
    STATUS BIT,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
GO
CREATE TABLE COMMENTS (
    ID INT IDENTITY PRIMARY KEY,
	CONTENT NVARCHAR(500),
    USERNAME VARCHAR(200),
	CREATEDATE DATETIME, 
    POST INT,
    IMAGE TEXT,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
    FOREIGN KEY (POST) REFERENCES POSTS(ID)
);
CREATE TABLE LIKECMTS (
    ID INT IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(200),
    COMMENT INT,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
    FOREIGN KEY (COMMENT) REFERENCES COMMENTS(ID)
);
GO
CREATE TABLE FRIENDS (
    ID INT IDENTITY PRIMARY KEY,
    USER_TARGET VARCHAR(200),
    USER_SRC VARCHAR(200),
    CREATEDATE DATETIME,
    STATUS BIT,
    FOREIGN KEY (USER_TARGET) REFERENCES USERS(USERNAME),
    FOREIGN KEY (USER_SRC) REFERENCES USERS(USERNAME)
);
GO
CREATE TABLE LIKEPOSTS (
    ID INT IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(200),
    POST INT,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
    FOREIGN KEY (POST) REFERENCES POSTS(ID)
);
GO
CREATE TABLE TRIPS (
    ID INT IDENTITY PRIMARY KEY,
    TRIPNAME NVARCHAR(500),
    STARTDATE DATE,
    ENDDATE DATE,
    CREATEDATE DATETIME,
    DESCRIPTION TEXT
);
GO
CREATE TABLE TRIPROLES (
    ID INT IDENTITY PRIMARY KEY,
    ROLE NVARCHAR(100)
);
GO
CREATE TABLE USERTRIPS (
    ID INT IDENTITY PRIMARY KEY,
    TRIPID INT,
    USERID VARCHAR(200),
    ROLE INT,
    FOREIGN KEY (TRIPID) REFERENCES TRIPS(ID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERNAME),
    FOREIGN KEY (ROLE) REFERENCES TRIPROLES(ID)
);
GO
CREATE TABLE NOTIFICATIONS (
    ID INT IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(200),
    CONTENT NVARCHAR(500),
    TYPE INT,
    POST INT,
    STATUS BIT,
    CREATEDATE DATETIME,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
    FOREIGN KEY (TYPE) REFERENCES TYPES(ID),
    FOREIGN KEY (POST) REFERENCES POSTS(ID)
);
GO
CREATE TABLE SHARES (
    ID INT IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(200),
    POST INT,
    CONTENT NVARCHAR(500),
    CREATEDATE DATETIME,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
    FOREIGN KEY (POST) REFERENCES POSTS(ID)
);
GO
CREATE TABLE CONVERSATIONS (
    ID INT IDENTITY PRIMARY KEY,
    NAME NVARCHAR(300),
    CREATEDAT DATETIME,
    AVATAR TEXT
);
GO
CREATE TABLE GROUPMEMBERS (
    ID INT IDENTITY PRIMARY KEY,
    CONVERSATION INT,
    USERNAME VARCHAR(200),
    TIMEJOIN DATETIME,
    FOREIGN KEY (CONVERSATION) REFERENCES CONVERSATIONS(ID),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
GO
CREATE TABLE MESSAGES (
    ID INT IDENTITY PRIMARY KEY,
    CONVERSATION INT,
    USERSRC VARCHAR(200),
    CONTENT NVARCHAR(500),
    CREATEDATE DATETIME,
    FOREIGN KEY (CONVERSATION) REFERENCES CONVERSATIONS(ID),
    FOREIGN KEY (USERSRC) REFERENCES USERS(USERNAME)
);
GO
CREATE TABLE POSTIMAGES (
    ID INT IDENTITY PRIMARY KEY,
    POSTID INT,
    IMAGE TEXT,
    FOREIGN KEY (POSTID) REFERENCES POSTS(ID)
);
GO
CREATE TABLE PLACES (
    ID INT IDENTITY PRIMARY KEY,
    NAMEPLACE NVARCHAR(500),
    --LONGITUDE VARCHAR(100),
    --LATITUDE VARCHAR(100),
    URLMAP VARCHAR(1000),
    ADDRESS NVARCHAR(1000),
    DESCRIPTION NVARCHAR(1000)
);
GO
CREATE TABLE PLACETRIPS (
    ID INT IDENTITY PRIMARY KEY,
    PLACEID INT,
    TRIPID INT,
    DATETIME DATETIME,
    NOTE NVARCHAR(500),
    FOREIGN KEY (PLACEID) REFERENCES PLACES(ID),
    FOREIGN KEY (TRIPID) REFERENCES TRIPS(ID)
);
GO
CREATE TABLE PLACEIMAGES (
    ID INT PRIMARY KEY,
    PLACEID INT,
    IMAGE TEXT,
    FOREIGN KEY (PLACEID) REFERENCES PLACES(ID)
);
go
CREATE TABLE IMAGES (
    ID INT IDENTITY PRIMARY KEY,
    IMAGE TEXT,
    CREATEDATE DATETIME,
    AVATARRURL TEXT,
    COVERURL TEXT,
    STATUS BIT,
	USERNAME VARCHAR(200),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);